# Generated by Django 3.1.3 on 2020-12-03 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalaxyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='galaxies.galaxy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_galaxies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('galaxy', 'user')},
            },
        ),
        migrations.AddField(
            model_name='galaxy',
            name='members',
            field=models.ManyToManyField(through='galaxies.GalaxyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
